config/routes.rb
Rails.application.routes.draw do

  get 'species/show'

  get 'species/index'

  get 'planets/index'

  get 'starships/index'

  get 'characters/index'
  
  resources :planets do
    get 'planets/:id'=> 'planets#show'
  end
  
  resources :starships do
    get 'starships/:id'=> 'starships#show'
  end
  
  resources :films do
    get 'films/:id'=> 'films#show'
  end
  
  resources :characters do
    get 'characters/:id'=> 'characters#show'
  end

  get 'films/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'films#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
require 'httparty'

class CharactersController < ApplicationController
  
  include HTTParty
  self.base_uri "https://swapi.co/api/"
  
  def show
    @character = self.class.get("/people/#{params[:id]}")
    @films = []
    @character['films'].each do |film|
      id = film.split('/')[5]
      @films.push(self.class.get("/films/#{id}"))
    end
    @vehicles = []
    @character['vehicles'].each do |vehicle|
      id = vehicle.split('/')[5]
      @vehicles.push(self.class.get("/vehicles/#{id}"))
    end
    @starships = []
    @character['starships'].each do |starship|
      id = starship.split('/')[5]
      @starships.push(self.class.get("/starships/#{id}"))
    end
    @characters_all = self.class.get("/people/")['results']
    @films_all = self.class.get("/films/")['results']
    @planets_all = self.class.get("/planets/")['results']
    @starships_all = self.class.get("/starships/")['results']
  end

  def index
    @characters = self.class.get("/people/")['results']
    @films = self.class.get("/films/")['results']
    @planets = self.class.get("/planets/")['results']
    @starships = self.class.get("/starships/")['results']
  end
end

app/controllers/films_controller.rb
require 'httparty'

class FilmsController < ApplicationController
  
  include HTTParty
  self.base_uri "https://swapi.co/api/"
  def show
    @film = self.class.get("/films/#{params[:id]}")
    @characters = []
    @film['characters'].each do |cha|
      id = cha.split('/')[5]
      @characters.push(self.class.get("/people/#{id}"))
    end
    @starships = []
    @film['starships'].each do |star|
      id = star.split('/')[5]
      @starships.push(self.class.get("/starships/#{id}"))
    end
    @planets = []
    @film['planets'].each do |planet|
      id = planet.split('/')[5]
      @planets.push(self.class.get("/planets/#{id}"))
    end
    @films_all = self.class.get("/films/")['results']
    @characters_all = self.class.get("/people/")['results']
    @planets_all = self.class.get("/planets/")['results']
    @starships_all = self.class.get("/starships/")['results']
  end

  def index
    @films = self.class.get("/films/")['results']
    @characters = self.class.get("/people/")['results']
    @planets = self.class.get("/planets/")['results']
    @starships = self.class.get("/starships/")['results']
  end
end

app/controllers/planets_controller.rb
require 'httparty'

class PlanetsController < ApplicationController
  
  include HTTParty
  self.base_uri "https://swapi.co/api/"
  
  def show
    @planet = self.class.get("/planets/#{params[:id]}")
    @films = []
    @planet['films'].each do |film|
      id = film.split('/')[5]
      @films.push(self.class.get("/films/#{id}"))
    end
    @residents = []
    @planet['residents'].each do |resident|
      id = resident.split('/')[5]
      @residents.push(self.class.get("/people/#{id}"))
    end
    @characters_all = self.class.get("/people/")['results']
    @films_all = self.class.get("/films/")['results']
    @planets_all = self.class.get("/planets/")['results']
    @starships_all = self.class.get("/starships/")['results']
  end

  def index
    @characters = self.class.get("/people/")['results']
    @films = self.class.get("/films/")['results']
    @planets = self.class.get("/planets/")['results']
    @starships = self.class.get("/starships/")['results']
  end
end

app/controllers/starships_controller.rb
require 'httparty'

class StarshipsController < ApplicationController
  
  include HTTParty
  self.base_uri "https://swapi.co/api/"
  
  def show
    @starship = self.class.get("/starships/#{params[:id]}")
    @films = []
    @starship['films'].each do |film|
      id = film.split('/')[5]
      @films.push(self.class.get("/films/#{id}"))
    end
    @pilots = []
    @starship['pilots'].each do |pilot|
      id = pilot.split('/')[5]
      @pilots.push(self.class.get("/people/#{id}"))
    end
    @characters_all = self.class.get("/people/")['results']
    @films_all = self.class.get("/films/")['results']
    @planets_all = self.class.get("/planets/")['results']
    @starships_all = self.class.get("/starships/")['results']
  end

  def index
    @characters = self.class.get("/people/")['results']
    @films = self.class.get("/films/")['results']
    @planets = self.class.get("/planets/")['results']
    @starships = self.class.get("/starships/")['results']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/characters/index.html.erb
<head>
  <style>
    /* Dropdown Button */
    .dropbtn {
      background-color: #4CAF50;
      color: white;
      padding: 10px;
      font-size: 14px;
      border: none;
      cursor: pointer;
    }
    
    /* Dropdown button on hover & focus */
    .dropbtn:hover, .dropbtn:focus {
      background-color: #3e8e41;
    }
    
    /* The search field */
    #myInput {
      border-box: box-sizing;
      background-image: url('searchicon.png');
      background-position: 14px 12px;
      background-repeat: no-repeat;
      font-size: 14px;
      padding: 12px 20px 12px 45px;
      border: none;
      border-bottom: 1px solid #ddd;
      justify-content: center;
    }
    
    /* The search field when it gets focus/clicked on */
    #myInput:focus {outline: 3px solid #ddd;}
    
    /* The container <div> - needed to position the dropdown content */
    .dropdown {
      position: relative;
      display: inline-block;
    }
    
    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f6f6f6;
      min-width: 230px;
      border: 1px solid #ddd;
      z-index: 1;
    }
    
    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }
    
    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #f1f1f1}
    
    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {display:block;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Search</button>
      <div id="myDropdown" class="dropdown-content">
        <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
        <% @films.each do |film| %>
        <% id = film['url'].split('/')[5] %>
        <p><%= link_to film['title'], film_url(id) %></p>
        <%end%>
        <% @characters.each do |character| %>
        <% id = character['url'].split('/')[5] %>
        <p><%= link_to character['name'], character_url(id) %></p>
        <%end%>
        <% @planets.each do |planet| %>
        <% id = planet['url'].split('/')[5] %>
        <p><%= link_to planet['name'], planet_url(id) %></p>
        <%end%>
        <% @starships.each do |starship| %>
        <% id = starship['url'].split('/')[5] %>
        <p><%= link_to starship['name'], starship_url(id) %></p>
        <%end%>
        </div>
      </div>
      <li class="nav-item active">
        <a class="nav-link" href="/films">Films <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/characters">Characters <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/planets">Planets <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/starships">Starships <span class="sr-only">(current)</span></a>
      </li>
    </ul>
</nav>
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table class="table table-hover table-striped">
  <thead class="black white-text">
    <tr>
      <th scope ="col">Name</th>
      <th scope ="col">Birth year</th>
      <th scope ="col">Gender</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |char| %>
      <% id = char['url'].split('/')[5] %>
    
      <tr>
        <td><%= char['name'] %></td>
        <td><%= char['birth_year'] %></td>
        <td><%= char['gender'] %></td>
        <td><%= link_to 'Show', character_url(id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<script>
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }
  
  function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
      txtValue = a[i].textContent || a[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
      } else {
        a[i].style.display = "none";
      }
    }
  }
</script>

app/views/characters/show.html.erb
<head>
  <style>
    /* Dropdown Button */
    .dropbtn {
      background-color: #4CAF50;
      color: white;
      padding: 10px;
      font-size: 14px;
      border: none;
      cursor: pointer;
    }
    
    /* Dropdown button on hover & focus */
    .dropbtn:hover, .dropbtn:focus {
      background-color: #3e8e41;
    }
    
    /* The search field */
    #myInput {
      border-box: box-sizing;
      background-image: url('searchicon.png');
      background-position: 14px 12px;
      background-repeat: no-repeat;
      font-size: 14px;
      padding: 12px 20px 12px 45px;
      border: none;
      border-bottom: 1px solid #ddd;
      justify-content: center;
    }
    
    /* The search field when it gets focus/clicked on */
    #myInput:focus {outline: 3px solid #ddd;}
    
    /* The container <div> - needed to position the dropdown content */
    .dropdown {
      position: relative;
      display: inline-block;
    }
    
    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f6f6f6;
      min-width: 230px;
      border: 1px solid #ddd;
      z-index: 1;
    }
    
    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }
    
    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #f1f1f1}
    
    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {display:block;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Search</button>
      <div id="myDropdown" class="dropdown-content">
        <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
        <% @films_all.each do |film| %>
        <% id = film['url'].split('/')[5] %>
        <p><%= link_to film['title'], film_url(id) %></p>
        <%end%>
        <% @characters_all.each do |character| %>
        <% id = character['url'].split('/')[5] %>
        <p><%= link_to character['name'], character_url(id) %></p>
        <%end%>
        <% @planets_all.each do |planet| %>
        <% id = planet['url'].split('/')[5] %>
        <p><%= link_to planet['name'], planet_url(id) %></p>
        <%end%>
        <% @starships_all.each do |starship| %>
        <% id = starship['url'].split('/')[5] %>
        <p><%= link_to starship['name'], starship_url(id) %></p>
        <%end%>
        </div>
      </div>
      <li class="nav-item active">
        <a class="nav-link" href="/films">Films <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/characters">Characters <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/planets">Planets <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/starships">Starships <span class="sr-only">(current)</span></a>
      </li>
    </ul>
</nav>
<p id="notice"><%= notice %></p>

<div class='panel panel-default container-fluid'>
  <div class="panel-heading"><h1 class='text-center'><%= @character['name'] %></h1></div>
    <table class='table table-bordered'>
    <tr>
      <th>Name:</th>
      <td><%=@character['name']%></td>
    </tr>
    <tr>
      <th>Hight:</th>
      <td><%=@character['height']%></td>
    </tr>
    <tr>
      <th>Mass:</th>
      <td><%= @character['mass'] %>kg</td>
    </tr>
    <tr>
      <th>Hair Color:</th>
      <td><%=@character['hair_color']%></td>
    </tr>
     <tr>
      <th>Skin Color:</th>
      <td><%=@character['skin_color']%></td>
    </tr>
     <tr>
      <th>Eye Color:</th>
      <td><%=@character['eye_color']%></td>
    </tr>
  </table>
</div>
<div class='row container-fluid'>
  <div class='col-md-6'>
    <div class='list-group list-group-flush'>
      <a href='/films' class='list-group-item'><h2>Films</h2></a>
      <% if !@character['films'].empty? %>
      <% @films.each do |film| %>
      <% id = film['url'].split('/')[5] %>
      <p><%= film['title'] %> <%= link_to 'Show', film_url(id) %></p>
      <%end%>
      <% else %>
      <a  class="list-group-item">No Films</a>
      <% end %>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='list-group list-group-flush'>
      <a href='/starships' class='list-group-item'><h2>Starships</h2></a>
      <% if !@character['starships'].empty? %>
      <% @starships.each do |starship| %>
      <% id = starship['url'].split('/')[5] %>
      <p><%= starship['name'] %> <%= link_to 'Show', starship_url(id) %></p>
      <%end%>
      <% else %>
      <a  class="list-group-item">No Starships</a>
      <% end %>
    </div>
  </div>
</div>

<center>
  <a href='/characters'><button class='btn btn-secondary btn-lg btn-block'>Back to Characters</button></a>
</center>

<script>
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }
  
  function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
      txtValue = a[i].textContent || a[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
      } else {
        a[i].style.display = "none";
      }
    }
  }
</script>

app/views/films/index.html.erb
<head>
  <style>
    /* Dropdown Button */
    .dropbtn {
      background-color: #4CAF50;
      color: white;
      padding: 10px;
      font-size: 14px;
      border: none;
      cursor: pointer;
    }
    
    /* Dropdown button on hover & focus */
    .dropbtn:hover, .dropbtn:focus {
      background-color: #3e8e41;
    }
    
    /* The search field */
    #myInput {
      border-box: box-sizing;
      background-image: url('searchicon.png');
      background-position: 14px 12px;
      background-repeat: no-repeat;
      font-size: 14px;
      padding: 12px 20px 12px 45px;
      border: none;
      border-bottom: 1px solid #ddd;
      justify-content: center;
    }
    
    /* The search field when it gets focus/clicked on */
    #myInput:focus {outline: 3px solid #ddd;}
    
    /* The container <div> - needed to position the dropdown content */
    .dropdown {
      position: relative;
      display: inline-block;
    }
    
    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f6f6f6;
      min-width: 230px;
      border: 1px solid #ddd;
      z-index: 1;
    }
    
    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }
    
    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #f1f1f1}
    
    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {display:block;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Search</button>
      <div id="myDropdown" class="dropdown-content">
        <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
        <% @films.each do |film| %>
        <% id = film['url'].split('/')[5] %>
        <p><%= link_to film['title'], film_url(id) %></p>
        <%end%>
        <% @characters.each do |character| %>
        <% id = character['url'].split('/')[5] %>
        <p><%= link_to character['name'], character_url(id) %></p>
        <%end%>
        <% @planets.each do |planet| %>
        <% id = planet['url'].split('/')[5] %>
        <p><%= link_to planet['name'], planet_url(id) %></p>
        <%end%>
        <% @starships.each do |starship| %>
        <% id = starship['url'].split('/')[5] %>
        <p><%= link_to starship['name'], starship_url(id) %></p>
        <%end%>
        </div>
      </div>
      <li class="nav-item active">
        <a class="nav-link" href="/films">Films <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/characters">Characters <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/planets">Planets <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/starships">Starships <span class="sr-only">(current)</span></a>
      </li>
    </ul>
</nav>
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table class="table table-hover table-striped">
  <thead class="black white-text">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Release Date</th>
      <th scope="col">Director</th>
       <th scope="col">Producer</th>
      <th scope="col">Episode</th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <% id = film['url'].split('/')[5] %>
    
      <tr class='clickable-row' data-href=film_url(id)>
        <td><%= film['title'] %></td>
        <td><%= film['release_date'] %></td>
        <td><%= film['director'] %></td>
        <td><%= film['producer'] %></td>
        <td><%= film['episode_id'] %></td>
        <td><%= link_to 'Show', film_url(id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<script>
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }
  
  function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
      txtValue = a[i].textContent || a[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
      } else {
        a[i].style.display = "none";
      }
    }
  }
</script>

app/views/films/show.html.erb
<head>
  <style>
    /* Dropdown Button */
    .dropbtn {
      background-color: #4CAF50;
      color: white;
      padding: 10px;
      font-size: 14px;
      border: none;
      cursor: pointer;
    }
    
    /* Dropdown button on hover & focus */
    .dropbtn:hover, .dropbtn:focus {
      background-color: #3e8e41;
    }
    
    /* The search field */
    #myInput {
      border-box: box-sizing;
      background-image: url('searchicon.png');
      background-position: 14px 12px;
      background-repeat: no-repeat;
      font-size: 14px;
      padding: 12px 20px 12px 45px;
      border: none;
      border-bottom: 1px solid #ddd;
      justify-content: center;
    }
    
    /* The search field when it gets focus/clicked on */
    #myInput:focus {outline: 3px solid #ddd;}
    
    /* The container <div> - needed to position the dropdown content */
    .dropdown {
      position: relative;
      display: inline-block;
    }
    
    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f6f6f6;
      min-width: 230px;
      border: 1px solid #ddd;
      z-index: 1;
    }
    
    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }
    
    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #f1f1f1}
    
    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {display:block;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Search</button>
      <div id="myDropdown" class="dropdown-content">
        <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
        <% @films_all.each do |film| %>
        <% id = film['url'].split('/')[5] %>
        <p><%= link_to film['title'], film_url(id) %></p>
        <%end%>
        <% @characters_all.each do |character| %>
        <% id = character['url'].split('/')[5] %>
        <p><%= link_to character['name'], character_url(id) %></p>
        <%end%>
        <% @planets_all.each do |planet| %>
        <% id = planet['url'].split('/')[5] %>
        <p><%= link_to planet['name'], planet_url(id) %></p>
        <%end%>
        <% @starships_all.each do |starship| %>
        <% id = starship['url'].split('/')[5] %>
        <p><%= link_to starship['name'], starship_url(id) %></p>
        <%end%>
        </div>
      </div>
      <li class="nav-item active">
        <a class="nav-link" href="/films">Films <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/characters">Characters <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/planets">Planets <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/starships">Starships <span class="sr-only">(current)</span></a>
      </li>
    </ul>
</nav>
<p id="notice"><%= notice %></p>
<div class='panel panel-default container-fluid'>
  <div class="panel-heading"><h1 class='text-center'><%= @film['title'] %></h1></div>
  <table class='table table-bordered'>
    <tr>
      <th>Episode:</th>
      <td><%=@film['episode_id']%></td>
    </tr>
    <tr>
      <th>Director:</th>
      <td><%=@film['director']%></td>
    </tr>
    <tr>
      <th>Producer:</th>
      <td><%= @film['producer'] %>kg</td>
    </tr>
    <tr>
      <th>Release Date:</th>
      <td><%=@film['release_date']%></td>
    </tr>
  </table>
  <div class="panel-heading"><h5 class='text-center'>Opening Crawl</h5></div>
  <div class="panel-body">
     <p><%= @film['opening_crawl'] %></p>
   </div>
</div>
<div class ="container-fluid">
  <div class = "row">
    <div class='col-md-4'>
      <div class='list-group list-group-flush'>
        <a href='/characters' class='list-group-item '><h2>Characters</h2></a>
        <% if !@film['characters'].empty? %>
        <% @characters.each do |character| %>
        <% id = character['url'].split('/')[5] %>
        <p><%= character['name'] %> <%= link_to 'Show', character_url(id) %></p>
        <%end%>
        <% else %>
        <a  class="list-group-item">No Starships</a>
        <% end %>
      </div>
    </div>
    <div class='col-md-4'>
      <div class='list-group list-group-flush'>
         <a href='/planets' class='list-group-item'><h2>Planets</h2></a>
          <% if !@film['planets'].empty? %>
          <% @planets.each do |planet| %>
          <% id = planet['url'].split('/')[5] %>
          <p><%= planet['name'] %> <%= link_to 'Show', planet_url(id) %></p>
          <%end%>
          <% else %>
          <a class="list-group-item">No Planets</a>
          <% end %>
      </div>
    </div>
    <div class='col-md-4'>
      <div class='list-group list-group-flush'>
        <a href='/starships' class='list-group-item'><h2>Starships</h2></a>
          <% if !@film['starships'].empty? %>
          <% @starships.each do |starship| %>
          <% id = starship['url'].split('/')[5] %>
          <p><%= starship['name'] %> <%= link_to 'Show', starship_url(id) %></p>
          <%end%>
          <% else %>
          <a  class="list-group-item">No Starships</a>
          <% end %>
      </div>
    </div>
  </div> <!--row-->
</div>

<center>
  <a href='/films'><button class='btn btn-secondary btn-lg btn-block'>Back to Films</button></a>
</center>

<script>
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }
  
  function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
      txtValue = a[i].textContent || a[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
      } else {
        a[i].style.display = "none";
      }
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>